#!/bin/bash
# Cherry Reader 发布构建脚本
# 用法: ./scripts/build_release.sh [版本号]
# 例如: ./scripts/build_release.sh 1.0.1

set -e

# 颜色定义
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
NC='\033[0m' # No Color

# 获取脚本所在目录
SCRIPT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
PROJECT_DIR="$(dirname "$SCRIPT_DIR")"
OUTPUT_DIR="$PROJECT_DIR/release_output"

# 版本号
VERSION=${1:-"1.0.0"}
BUILD_NUMBER=$(date +%Y%m%d%H%M)

echo -e "${GREEN}======================================${NC}"
echo -e "${GREEN}  Cherry Reader 构建脚本${NC}"
echo -e "${GREEN}  版本: ${VERSION}+${BUILD_NUMBER}${NC}"
echo -e "${GREEN}======================================${NC}"

cd "$PROJECT_DIR"

# 创建输出目录
rm -rf "$OUTPUT_DIR"
mkdir -p "$OUTPUT_DIR"

# 更新 .env
echo "# Auto generated by build script" > .env
echo "APP_VERSION=$VERSION" >> .env

# 获取依赖
echo -e "\n${YELLOW}[1/5] 获取依赖...${NC}"
flutter pub get

# 构建 Android APK
echo -e "\n${YELLOW}[2/5] 构建 Android APK...${NC}"
flutter build apk --release \
    --build-name="$VERSION" \
    --build-number="$BUILD_NUMBER"

# 复制 APK
cp build/app/outputs/flutter-apk/app-release.apk \
   "$OUTPUT_DIR/CherryReader-$VERSION-android.apk"
echo -e "${GREEN}  ✓ APK 已生成${NC}"

# 构建分架构 APK
echo -e "\n${YELLOW}[3/5] 构建分架构 APK...${NC}"
flutter build apk --release --split-per-abi \
    --build-name="$VERSION" \
    --build-number="$BUILD_NUMBER"

cp build/app/outputs/flutter-apk/app-arm64-v8a-release.apk \
   "$OUTPUT_DIR/CherryReader-$VERSION-arm64.apk" 2>/dev/null || true
cp build/app/outputs/flutter-apk/app-armeabi-v7a-release.apk \
   "$OUTPUT_DIR/CherryReader-$VERSION-arm32.apk" 2>/dev/null || true
cp build/app/outputs/flutter-apk/app-x86_64-release.apk \
   "$OUTPUT_DIR/CherryReader-$VERSION-x86_64.apk" 2>/dev/null || true
echo -e "${GREEN}  ✓ 分架构 APK 已生成${NC}"

# 构建 Web
echo -e "\n${YELLOW}[4/5] 构建 Web 版本...${NC}"
flutter build web --release \
    --build-name="$VERSION" \
    --build-number="$BUILD_NUMBER"

cd build
zip -r "$OUTPUT_DIR/CherryReader-$VERSION-web.zip" web
cd "$PROJECT_DIR"
echo -e "${GREEN}  ✓ Web 版本已生成${NC}"

# macOS (仅在 macOS 系统上构建)
if [[ "$OSTYPE" == "darwin"* ]]; then
    echo -e "\n${YELLOW}[5/5] 构建 macOS 版本...${NC}"
    flutter build macos --release \
        --build-name="$VERSION" \
        --build-number="$BUILD_NUMBER"

    cd "build/macos/Build/Products/Release"
    zip -r "$OUTPUT_DIR/CherryReader-$VERSION-macos.zip" *.app
    cd "$PROJECT_DIR"
    echo -e "${GREEN}  ✓ macOS 版本已生成${NC}"
else
    echo -e "\n${YELLOW}[5/5] 跳过 macOS 构建 (非 macOS 系统)${NC}"
fi

# 显示结果
echo -e "\n${GREEN}======================================${NC}"
echo -e "${GREEN}  构建完成！${NC}"
echo -e "${GREEN}======================================${NC}"
echo -e "\n输出目录: $OUTPUT_DIR"
echo -e "\n生成的文件:"
ls -lh "$OUTPUT_DIR"

echo -e "\n${YELLOW}下一步:${NC}"
echo "1. 创建 tag:    git tag v$VERSION"
echo "2. 推送 tag:    git push origin v$VERSION"
echo "3. 或手动上传到 GitHub Release"
